/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* --- Forward Declarations --- */
void _gampil_main(unsigned char** args);
int add(int a, int b);
int sub(int a, int b);
int mul(int a, int b);


int add(int a, int b) {
    return (a + b);
}

int sub(int a, int b) {
    return (a - b);
}

int mul(int a, int b) {
    return (a * b);
}

void _gampil_main(unsigned char** args) {
    int x = 10LL;
    int y = 3LL;
    printf("x = %d\n", x);
    printf("y = %d\n", y);
    printf("x + y = %d\n", add(x, y));
    printf("x - y = %d\n", sub(x, y));
    printf("x * y = %d\n", mul(x, y));
    float pi = 3.14;
    printf("pi = %g\n", pi);
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_main((unsigned char**)argv);
    return 0;
}
