/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_algo(unsigned char** args);
short add(short a, short b);
short sub(short a, short b);
short mul(short a, short b);


short add(short a, short b) {
(void)a;
(void)b;
    return (a + b);
}

short sub(short a, short b) {
(void)a;
(void)b;
    return (a - b);
}

short mul(short a, short b) {
(void)a;
(void)b;
    return (a * b);
}

void _gampil_algo(unsigned char** args) {
    (void)args;
    short x = 10;
    short y = 3;
    printf("x = %d\\n", x);
    printf("y = %d\\n", y);
    printf("x + y = %d\\n", add(x, y));
    printf("x - y = %d\\n", sub(x, y));
    printf("x * y = %d\\n", mul(x, y));
    float pi = 3.14;
    printf("pi = %g\\n", pi);
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_algo((unsigned char**)argv);
    return 0;
}
