/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_main(unsigned char** args);


void _gampil_main(unsigned char** args) {
    (void)args;
    short arr[3] = {1, 3, 5};
    printf("arr[0] = %d\\n", arr[0]);
    printf("arr[1] = %d\\n", arr[1]);
    printf("arr[2] = %d\\n", arr[2]);
    short target = 42;
    short* ptr = &target;
    printf("*ptr = %d\\n", ptr[0]);
    arr[1] = 99;
    printf("arr[1] after assign = %d\\n", arr[1]);
    printf("Arrays OK\\n");
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_main((unsigned char**)argv);
    return 0;
}
