/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_algo(unsigned char** args);


void _gampil_algo(unsigned char** args) {
    (void)args;
    long _varmult_4_5_shared = 1000;
    short a = _varmult_4_5_shared;
    short b = _varmult_4_5_shared;
    short c = _varmult_4_5_shared;
    printf("a: %d, b: %d, c: %d\\n", a, b, c);
    register int varReg __asm__("eax") = 20;
    printf("varReg before mov: %d\\n", varReg);
    __asm__ ("mov %1, %0" : "=g"(varReg) : "g"(42));
    printf("varReg after mov: %d\\n", varReg);
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_algo((unsigned char**)argv);
    return 0;
}
