/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* --- Forward Declarations --- */
void _gampil_main(unsigned char** args);


void _gampil_main(unsigned char** args) {
    int x = 5LL;
    /* --- Parallel Guard Block --- */
    {
        int _guard0 = (
(x > 3LL));
        int _guard1 = (
(x == 5LL));
        int _guard2 = (
(x < 10LL));
        if (_guard2) { _guard0 = 0; _guard1 = 0; }
        if (_guard0) {
            printf("x is greater than 3\n");
        }
        if (_guard1) {
            printf("x is equal to 5\n");
        }
        if (_guard2) {
            printf("x is less than 10 (exclusive)\n");
        }
    } /* --- end Guard Block --- */
    int a = 1LL;
    int b = 0LL;
    if ((a && !(b))) {
        printf("a is true, b is false\n");
    }
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_main((unsigned char**)argv);
    return 0;
}
