/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_algo();


void _gampil_algo() {
    long x = 10;
    /* --- Parallel Guard Block --- */
    {
        int _else_flag = 1;
        int _guard0 = ((x < 5));
        if (_guard0) _else_flag = 0;
        int _guard1 = ((x == 5));
        if (_guard1) _else_flag = 0;
        int _guard2 = (_else_flag);
        if (_guard2) _else_flag = 0;
        if (_guard0) {
            printf("x is less than 5\\n");
        }
        if (_guard1) {
            printf("x is 5\\n");
        }
        if (_guard2) {
            printf("x is greater than 5 (else block hit)\\n");
        }
    } /* --- end Guard Block --- */
    long y = 20;
    /* --- Parallel Guard Block --- */
    {
        int _else_flag = 1;
        int _guard0 = ((y == 10));
        if (_guard0) _else_flag = 0;
        int _guard1 = (((y > 15) && _else_flag));
        if (_guard1) _else_flag = 0;
        if (_guard0) {
            printf("y is 10\\n");
        }
        if (_guard1) {
            printf("y is > 15 and no previous conditions met\\n");
        }
    } /* --- end Guard Block --- */
    /* --- Parallel Guard Block --- */
    {
        int _else_flag = 1;
        int _guard0 = ((y == 20));
        if (_guard0) _else_flag = 0;
        int _guard1 = (((y > 15) || (_else_flag && 0)));
        if (_guard1) _else_flag = 0;
        if (_guard0) {
            printf("y is 20\\n");
        }
        if (_guard1) {
            printf("y > 15 or (else and false)\\n");
        }
    } /* --- end Guard Block --- */
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_algo((unsigned char**)argv);
    return 0;
}
