/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_main();


void _gampil_main() {
    struct { long _0; double _1; } my_struct = {5, 3.14};
    long long my_dynamic = 100;
    my_dynamic += 50;
    my_dynamic = (my_dynamic * 2);
    printf("Struct field 0: %d\\n", my_struct._0);
    printf("Struct field 1: %f\\n", my_struct._1);
    short* my_ptr = NULL;
    long long c = (3.14 * _Complex_I);
    c = (c + 1);
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_main((unsigned char**)argv);
    return 0;
}
