/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_main(unsigned char** args);


void _gampil_main(unsigned char** args) {
    (void)args;
    short x = 10;
    /* --- Parallel Guard Block --- */
    {
        int _else_flag = 1;
        int _guard0 = ((x < 5));
        if (_guard0) _else_flag = 0;
        int _guard1 = ((x < 8));
        if (_guard1) _else_flag = 0;
        int _guard2 = (_else_flag);
        if (_guard2) _else_flag = 0;
        if (_guard0) {
            printf("Less than 5\\n");
        }
        if (_guard1) {
            printf("Less than 8\\n");
        }
        if (_guard2) {
            printf("Default fallback reached!\\n");
        }
    } /* --- end Guard Block --- */
    {
        long _tmp_arr_18_0[3] = {1, 2, 3};
        for (int _idx_18 = 0; _idx_18 < 3; _idx_18++) {
            long i = _tmp_arr_18_0[_idx_18];
            printf("i = %d\\n", i);
        }
    }
    short arr1[3] = {10, 20, 30};
    short arr2[3] = {100, 200, 300};
    {
        for (int _idx_25 = 0; _idx_25 < 3; _idx_25++) {
            short val1 = arr1[_idx_25];
            short val2 = arr2[_idx_25];
            printf("val1: %d, val2: %d\\n", val1, val2);
        }
    }
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_main((unsigned char**)argv);
    return 0;
}
