/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_algo(unsigned char** args);


void _gampil_algo(unsigned char** args) {
    (void)args;
    long b = 42;
    unsigned char* greeting = ({ char* _fb = (char*)malloc(1024); snprintf(_fb, 1024, "hello %lld\n", (long long)b); (void*)_fb; });
    printf("%s", greeting);
    long x = 100;
    printf(({ char* _fb = (char*)malloc(1024); snprintf(_fb, 1024, "x is %lld\n", (long long)x); (void*)_fb; }));
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_algo((unsigned char**)argv);
    return 0;
}
