/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_algo(unsigned char** args);


void _gampil_algo(unsigned char** args) {
    (void)args;
    printf("Hello, World!\\n");
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_algo((unsigned char**)argv);
    return 0;
}
