/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_main(unsigned char** args);


void _gampil_main(unsigned char** args) {
    (void)args;
    short nums[5] = {10, 20, 30, 40, 50};
    {
        for (int _idx_6 = 0; _idx_6 < 5; _idx_6++) {
            short val = nums[_idx_6];
            printf("%d ", val);
        }
    }
    printf("\\n");
    short counter = 0;
    while ((counter < 5)) {
        counter += 1;
        printf("counter: %d\\n", counter);
    }
    short x = 3;
    while (1) {
        /* --- Parallel Guard Block --- */
        {
            int _else_flag = 1;
            int _guard0 = ((!(x) > 0));
            if (_guard0) _else_flag = 0;
            if (_guard0) {
                break;
            }
        } /* --- end Guard Block --- */
        printf("x = %d\\n", x);
        x -= 1;
    }
    printf("Done!\\n");
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_main((unsigned char**)argv);
    return 0;
}
