/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* --- Forward Declarations --- */
void _gampil_main(unsigned char** args);


void _gampil_main(unsigned char** args) {
    (void)args;
    int nums[5] = {10LL, 20LL, 30LL, 40LL, 50LL};
    for (int _idx_val = 0; _idx_val < 5; _idx_val++) {
        int val = nums[_idx_val];
        printf("%d ", val);
    }
    printf("\n");
    int counter = 0LL;
    while ((counter < 5LL)) {
        counter += 1LL;
        printf("counter: %d\n", counter);
    }
    int x = 3LL;
    while (1) {
        if ((!(x) > 0LL)) {
            break;
        }
        printf("x = %d\n", x);
        x -= 1LL;
    }
    printf("Done!\n");
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_main((unsigned char**)argv);
    return 0;
}
