/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_algo();


void _gampil_algo() {
    long _varmult_3_5_0 = 3;
    long _varmult_3_5_1 = 5;
    signed char a = _varmult_3_5_0;
    short b = _varmult_3_5_1;
    printf("a = %d, b = %d\\n", a, b);
    long long _varmult_7_5_0 = b;
    long long _varmult_7_5_1 = a;
    a = _varmult_7_5_0;
    b = _varmult_7_5_1;
    printf("swapped: a = %d, b = %d\\n", a, b);
    short y = 0;
    long _varmult_12_5_shared = 7;
    short x = _varmult_12_5_shared;
    y = _varmult_12_5_shared;
    signed char z = _varmult_12_5_shared;
    printf("broadcast: x = %d, y = %d, z = %d\\n", x, y, z);
    short j = 0;
    long _varmult_17_5_0 = 10;
    long _varmult_17_5_1 = 20;
    short i = _varmult_17_5_0;
    j = _varmult_17_5_1;
    long _varmult_18_5_0 = 1;
    long _varmult_18_5_1 = 2;
    long _varmult_18_5_2 = 3;
    signed char k = _varmult_18_5_0;
    j = _varmult_18_5_1;
    i = _varmult_18_5_2;
    printf("mixed: k = %d, j = %d, i = %d\\n", k, j, i);
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_algo((unsigned char**)argv);
    return 0;
}
