#!/usr/bin/env python3
"""
============================================================
  Gampil Programming Language — Python Runtime Bridge
  gampil_runtime.py

  This runtime handles all `let` (dynamic-typed) variables
  and operations in Gampil programs.

  Called by the compiled Gampil executable as:
      system("python gampil_runtime.py <snippet_file.py>")

  The snippet file is a small Python script generated by
  the Gampil executable at runtime.
============================================================
"""

import sys
import os
import pickle
try:
    import builtins
except ImportError:
    import __builtin__ as builtins

# ── Gampil built-in functions (Python side) ─────────────────

def gampil_printf(fmt, *args):
    """C-style printf equivalent."""
    try:
        # Handle %d, %f, %s, %g substitutions
        result = fmt
        i = 0
        out_parts = []
        idx = 0
        while idx < len(fmt):
            if fmt[idx] == '%' and idx + 1 < len(fmt):
                spec = fmt[idx+1]
                if spec in ('d', 'i'):
                    out_parts.append(str(int(args[i])))
                    i += 1; idx += 2; continue
                elif spec in ('f',):
                    out_parts.append(f"{float(args[i]):.6f}")
                    i += 1; idx += 2; continue
                elif spec in ('g',):
                    out_parts.append(f"{float(args[i]):g}")
                    i += 1; idx += 2; continue
                elif spec in ('s',):
                    out_parts.append(str(args[i]))
                    i += 1; idx += 2; continue
                elif spec == '%':
                    out_parts.append('%'); idx += 2; continue
            out_parts.append(fmt[idx])
            idx += 1
        print(''.join(out_parts), end='')
    except Exception:
        print(fmt, *args, end='')

def gampil_printn(*args):
    """Print with newline."""
    print(*args)

def gampil_print(*args):
    """Basic print (no newline)."""
    print(*args, end='')

# ── Gampil type wrappers ─────────────────────────────────────

class GampilInt:
    """Represents num16/num32/num64 dynamically."""
    __slots__ = ('value',)
    def __init__(self, v=0): self.value = int(v)
    def __repr__(self): return str(self.value)
    def __str__(self):  return str(self.value)
    def __add__(self, o): return GampilInt(self.value + int(o))
    def __sub__(self, o): return GampilInt(self.value - int(o))
    def __mul__(self, o): return GampilInt(self.value * int(o))
    def __floordiv__(self, o): return GampilInt(self.value // int(o))
    def __mod__(self, o): return GampilInt(self.value % int(o))
    def __int__(self): return self.value

class GampilFloat:
    """Represents rat32/rat64/rat128 dynamically."""
    __slots__ = ('value',)
    def __init__(self, v=0.0): self.value = float(v)
    def __repr__(self): return str(self.value)
    def __str__(self):  return str(self.value)
    def __add__(self, o): return GampilFloat(self.value + float(o))
    def __sub__(self, o): return GampilFloat(self.value - float(o))
    def __mul__(self, o): return GampilFloat(self.value * float(o))
    def __truediv__(self, o): return GampilFloat(self.value / float(o))
    def __float__(self): return self.value

class GampilTable:
    """Represents field / array types dynamically."""
    def __init__(self, *elements, **kwargs):
        self.elements = list(elements)
        for k, v in kwargs.items():
            setattr(self, k, v)
    def __getitem__(self, i): return self.elements[i]
    def __setitem__(self, i, v): self.elements[i] = v
    def __len__(self): return len(self.elements)
    def __iter__(self): return iter(self.elements)
    def __repr__(self): return f"Table({self.elements}, kwargs={self.__dict__})"

# ── Gampil runtime environment ───────────────────────────────

class GampilRuntime:
    """
    Provides the execution environment for Gampil Python snippets.
    All `let` variable operations happen here.
    """

    def __init__(self):
        self.globals = {
            # Built-in functions
            'printf':  gampil_printf,
            'printn':  gampil_printn,
            'print':   gampil_print,
            'println': gampil_printn,

            # Type constructors
            'GampilInt':   GampilInt,
            'GampilFloat': GampilFloat,
            'GampilTable': GampilTable,

            # Standard Python builtins that Gampil code might need
            'len':    builtins.len,
            'range':  builtins.range,
            'int':    builtins.int,
            'float':  builtins.float,
            'str':    builtins.str,
            'list':   builtins.list,
            'set':    builtins.set,
            'tuple':  builtins.tuple,
            'frozenset': getattr(builtins, 'frozenset', frozenset),
            'print':  builtins.print,
            'input':  builtins.input,
            'abs':    builtins.abs,
            'max':    builtins.max,
            'min':    builtins.min,
            'sum':    builtins.sum,
            'sorted': builtins.sorted,
            'reversed': builtins.reversed,
            'enumerate': builtins.enumerate,
            'zip':    builtins.zip,
            'map':    builtins.map,
            'filter': builtins.filter,
            'type':   builtins.type,
            'isinstance': builtins.isinstance,
        }
        self.state_file = "_gampil_state.pkl"
        if os.path.exists(self.state_file):
            try:
                with open(self.state_file, 'rb') as f:
                    saved = pickle.load(f)
                    self.globals.update(saved)
            except Exception:
                pass

    def _save_state(self):
        try:
            to_save = {k: v for k, v in self.globals.items()
                       if not k.startswith('__') and not callable(v) and type(v) != type(sys)}
            with open(self.state_file, 'wb') as f:
                pickle.dump(to_save, f)
        except Exception:
            pass

    def execute_file(self, path):
        """Execute a Python snippet file in the Gampil runtime environment."""
        try:
            with open(path, 'r', encoding='utf-8') as f:
                code = f.read()
            exec(compile(code, path, 'exec'), self.globals)
            self._save_state()
        except FileNotFoundError:
            print(f"[gampil_runtime] Error: snippet file '{path}' not found.",
                  file=sys.stderr)
            sys.exit(1)
        except SyntaxError as e:
            print(f"[gampil_runtime] Python syntax error in snippet: {e}",
                  file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"[gampil_runtime] Runtime error: {e}", file=sys.stderr)
            sys.exit(1)

    def execute_code(self, code_str):
        """Execute a Python code string directly."""
        try:
            exec(compile(code_str, '<gampil_snippet>', 'exec'), self.globals)
        except Exception as e:
            print(f"[gampil_runtime] Runtime error: {e}", file=sys.stderr)
            sys.exit(1)


# ── Entry point ──────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print("Usage: python gampil_runtime.py <snippet.py>", file=sys.stderr)
        sys.exit(1)

    snippet_file = sys.argv[1]
    runtime = GampilRuntime()
    runtime.execute_file(snippet_file)


if __name__ == '__main__':
    main()
