/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
long long std_print_num(long long val);
long long std_print_py(long long py_val);
long long std_abs(long long py_val);
long long std_add_asm(long long a, long long b);
long long std_sub_asm(long long a, long long b);
long long std_len(long long py_iterable);
long long std_exit(long long code);


long long std_print_num(long long val) {
(void)val;
    {
        FILE* _pyf = fopen("_gampil_pysnip.py", "w");
        if (_pyf) {
            fprintf(_pyf, "%s", "py_val = int(val)\n");
            fclose(_pyf);
        }
        const char* _env_py = getenv("GAMPIL_PYTHON");
        const char* _py = _env_py ? _env_py : "python";
        const char* _env_rt = getenv("GAMPIL_RUNTIME");
        const char* _rt = _env_rt ? _env_rt : "D:\\Gampil The Language\\compiler\\..\\runtime\\gampil_runtime.py";
        char _cmd[2048];
        snprintf(_cmd, sizeof(_cmd), "%s \"%s\" _gampil_pysnip.py", _py, _rt);
        system(_cmd);
    }
    long long py_val = 0;
    printf(py_val);
    return 0;
}

long long std_print_py(long long py_val) {
(void)py_val;
    printf(py_val);
    return 0;
}

long long std_abs(long long py_val) {
(void)py_val;
    {
        FILE* _pyf = fopen("_gampil_pysnip.py", "w");
        if (_pyf) {
            fprintf(_pyf, "%s", "g_val = py_val\nwith open('_gampil_pyout.txt', 'w') as _f:\n    _f.write(str(g_val))\n");
            fclose(_pyf);
        }
        const char* _env_py = getenv("GAMPIL_PYTHON");
        const char* _py = _env_py ? _env_py : "python";
        const char* _env_rt = getenv("GAMPIL_RUNTIME");
        const char* _rt = _env_rt ? _env_rt : "D:\\Gampil The Language\\compiler\\..\\runtime\\gampil_runtime.py";
        char _cmd[2048];
        snprintf(_cmd, sizeof(_cmd), "%s \"%s\" _gampil_pysnip.py", _py, _rt);
        system(_cmd);
    }
    long long g_val = ({ long long _gv = 0; FILE* _gf = fopen("_gampil_pyout.txt", "r"); if(_gf){ fscanf(_gf, "%lld", &_gv); fclose(_gf); } _gv; });
    /* --- Parallel Guard Block --- */
    {
        int _else_flag = 1;
        int _guard0 = ((g_val < 0));
        if (_guard0) _else_flag = 0;
        if (_guard0) {
            g_val = -(g_val);
        }
    } /* --- end Guard Block --- */
    return g_val;
}

long long std_add_asm(long long a, long long b) {
(void)a;
(void)b;
    long long res;
    __asm__ ("mov %1, %0" : "=g"(res) : "g"(a));
    __asm__ ("add %1, %0" : "=g"(res) : "g"(b));
    return res;
}

long long std_sub_asm(long long a, long long b) {
(void)a;
(void)b;
    long long res;
    __asm__ ("mov %1, %0" : "=g"(res) : "g"(a));
    __asm__ ("sub %1, %0" : "=g"(res) : "g"(b));
    return res;
}

long long std_len(long long py_iterable) {
(void)py_iterable;
    {
        FILE* _pyf = fopen("_gampil_pysnip.py", "w");
        if (_pyf) {
            fprintf(_pyf, "%s", "py_len = len(py_iterable)\n");
            fclose(_pyf);
        }
        const char* _env_py = getenv("GAMPIL_PYTHON");
        const char* _py = _env_py ? _env_py : "python";
        const char* _env_rt = getenv("GAMPIL_RUNTIME");
        const char* _rt = _env_rt ? _env_rt : "D:\\Gampil The Language\\compiler\\..\\runtime\\gampil_runtime.py";
        char _cmd[2048];
        snprintf(_cmd, sizeof(_cmd), "%s \"%s\" _gampil_pysnip.py", _py, _rt);
        system(_cmd);
    }
    long long py_len = 0;
    {
        FILE* _pyf = fopen("_gampil_pysnip.py", "w");
        if (_pyf) {
            fprintf(_pyf, "%s", "g_len = py_len\nwith open('_gampil_pyout.txt', 'w') as _f:\n    _f.write(str(g_len))\n");
            fclose(_pyf);
        }
        const char* _env_py = getenv("GAMPIL_PYTHON");
        const char* _py = _env_py ? _env_py : "python";
        const char* _env_rt = getenv("GAMPIL_RUNTIME");
        const char* _rt = _env_rt ? _env_rt : "D:\\Gampil The Language\\compiler\\..\\runtime\\gampil_runtime.py";
        char _cmd[2048];
        snprintf(_cmd, sizeof(_cmd), "%s \"%s\" _gampil_pysnip.py", _py, _rt);
        system(_cmd);
    }
    long long g_len = ({ long long _gv = 0; FILE* _gf = fopen("_gampil_pyout.txt", "r"); if(_gf){ fscanf(_gf, "%lld", &_gv); fclose(_gf); } _gv; });
    return g_len;
}

long long std_exit(long long code) {
(void)code;
    {
        FILE* _pyf = fopen("_gampil_pysnip.py", "w");
        if (_pyf) {
            fprintf(_pyf, "%s", "py_code = int(code)\n");
            fclose(_pyf);
        }
        const char* _env_py = getenv("GAMPIL_PYTHON");
        const char* _py = _env_py ? _env_py : "python";
        const char* _env_rt = getenv("GAMPIL_RUNTIME");
        const char* _rt = _env_rt ? _env_rt : "D:\\Gampil The Language\\compiler\\..\\runtime\\gampil_runtime.py";
        char _cmd[2048];
        snprintf(_cmd, sizeof(_cmd), "%s \"%s\" _gampil_pysnip.py", _py, _rt);
        system(_cmd);
    }
    long long py_code = 0;
    {
        FILE* _pyf = fopen("_gampil_pysnip.py", "w");
        if (_pyf) {
            fprintf(_pyf, "%s", "exit(py_code)\n");
            fclose(_pyf);
        }
        const char* _env_py = getenv("GAMPIL_PYTHON");
        const char* _py = _env_py ? _env_py : "python";
        const char* _env_rt = getenv("GAMPIL_RUNTIME");
        const char* _rt = _env_rt ? _env_rt : "D:\\Gampil The Language\\compiler\\..\\runtime\\gampil_runtime.py";
        char _cmd[2048];
        snprintf(_cmd, sizeof(_cmd), "%s \"%s\" _gampil_pysnip.py", _py, _rt);
        system(_cmd);
    }
    return 0;
}

int main(int argc, char** argv) {
    (void)argc;
    (void)argv;
    return 0;
}
