/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
static yyconst short int yy_accept[215] =
    {   0,
        0,    0,   31,   29,   28,   27,   12,   29,   23,   25,
       29,   23,   29,   21,   21,   27,   24,   24,   24,   26,
        2,   29,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   25,   12,   27,   24,    0,    1,    0,
        0,    0,    0,    0,   21,   21,   22,   22,   21,    0,
        0,    0,    0,    0,    0,    0,   25,   26,   26,    2,
        0,    3,   26,   15,    5,   26,   26,   26,    6,   26,
       26,    9,   11,   26,   26,   26,   26,    0,    0,    0,
        0,    0,    0,    0,    4,    0,    0,    0,    0,    0,
       22,   22,   21,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   22,    0,    0,    0,    0,    0,    0,   21,
        0,   21,   10,    7,   26,   26,   18,   12,   26,   26,
       26,   26,   26,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   22,    0,    0,    0,    0,
        0,    0,   21,    0,   21,    0,   22,    0,    0,   21,
       22,   21,   21,   21,    8,   26,   26,   13,   26,   19,
       26,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       22,    0,    0,   21,   22,   21,   21,   21,   22,   22,
       22,    0,   20,   14,   26,   16,    0,    0,    0,    0,
       22,   22,   22,    0,    0,    0,   22,   17,    0,    0,

        0,    0,   22,   22,   22,    0,    0,   22,   22,    0,
        0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    1,
        1,    6,    9,    1,   10,   11,    6,   12,   13,   14,
       14,   14,   14,   14,   14,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   21,   20,   20,   22,   20,
       23,   23,   23,   23,   23,   23,   23,   24,   25,   23,
       23,   23,   23,   23,   26,   23,   23,   27,   23,   23,
        1,   28,    1,    6,   29,   30,   31,   32,   20,   33,

       34,   35,   23,   36,   37,   23,   38,   39,   23,   40,
       41,   23,   42,   43,   44,   45,   46,   47,   48,   49,
       23,   23,    1,   50,    1,   51,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    5,    5,    5,    5,    1,    1,    1,    1,    6,
        6,    6,    7,    8,    7,    8,    7,    9,    7,    1,
       10,   10,    6,    6,   10,    7,    7,    7,    7,    8,
        8,    7,    8,    7,    8,    8,    8,    7,    8,    1,
        1
    } ;

static yyconst short int yy_base[228] =
    {   0,
        0,    0,  504, 1012, 1012,   49,  480,   48,  463,  462,
       46,   45,   49,   67,  106,   52,   49, 1012,   51,   71,
        0,  449,   90,   97,  110,  124,  132,  138,  144,  148,
      156,  171,  183,   40, 1012,   84, 1012,   70,  121,  167,
      431,   63,  176,  191,  215,  254,  219,  248,   85,  435,
      392,   97,  391,  385,  197,  259,  381,  265,  272,    0,
      360, 1012,  277,  281,  285,  289,  293,  299,  303,  307,
      311,  315,  327,  335,  340,  345,  349,  136,   65,    0,
      340,  343,  334,  341, 1012,    0,  327,  333,  322,  334,
      353,  366,  103,  340,  322,  156,  316,  315,  380,  384,

      163,  389,  393,  167,  397,  168,  404,  238,  411,  416,
      314,  420,  424,  428,  432,  436,  440,  444,  448,  455,
      459,  463,  469,  508,  287,  294,  284,  296,  559,  282,
      268,  232,  239,  179,  473,  477,  211,  488,  211,  599,
      245,  603,  607,  226,  611,  615,  619,  623,  630,  225,
      637,  217,  642,  216,  646,  650,  655,  660,  664,  668,
      678,  712,    0,  194,  190,  763,    0,  189,  186,  673,
      686,  682,  690,  189,  712,  186,  720,  178,  724,  732,
      763,  743,  771,  775,  782,  786,  152,  150,  143,  129,
      790,  794,  812,  817,  821,  825,  830,  834,  125,  105,

      838,  842,  848,  852,  856,   99,   93,  860,  878,   84,
       78,   64,   46, 1012,  907,  917,  923,  933,  943,  951,
      959,  964,  969,  975,  981,  991, 1001
    } ;

static yyconst short int yy_def[228] =
    {   0,
      214,    1,  214,  214,  214,  214,  214,  215,  214,  214,
      216,  214,  214,  214,  214,  214,  214,  214,  214,  217,
      218,  219,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  214,  214,  214,  214,  215,  214,  220,
      214,  216,  221,  214,  214,  214,  214,  214,   15,   15,
      214,  214,  214,  214,  214,  214,  214,  217,  217,  218,
      219,  214,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  215,  216,  222,
      214,  214,  214,  214,  214,  223,  214,  214,  214,  214,
      214,  214,   46,   46,  214,  214,  214,  214,  214,  214,

      214,  214,  214,  214,  214,  214,  214,  214,  224,   49,
      110,   15,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  225,   93,  143,   46,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  217,  217,  217,  217,  217,  217,
      217,  226,  124,  214,  214,  227,  129,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  217,  217,  217,  217,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  217,  214,  214,

      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,    0,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214
    } ;

static yyconst short int yy_nxt[1064] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,    9,   12,
       13,   14,   15,   15,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   20,   22,
       23,   24,   20,   25,   26,   20,   27,   20,   20,   28,
       29,   30,   31,   20,   32,   20,   20,   33,   20,   34,
       35,   36,   39,   39,   36,   44,   45,   46,   46,   46,
       47,   47,   47,   47,   36,   57,   37,   36,   37,   57,
       39,   41,   39,   43,   39,   40,   41,   48,   49,   50,
       50,   50,   58,   58,   58,   58,   36,   51,   52,   57,
       43,   53,   43,   54,   42,   55,   49,   40,   51,   36,

       52,   58,   58,   58,   58,  107,  107,   53,   58,   58,
       58,   58,   38,   55,   93,   54,   48,   50,   50,   50,
       50,   58,   58,   58,   58,   78,  213,   52,   79,   63,
       65,   99,  212,   64,   56,   58,   58,   58,   58,   52,
       39,  211,   66,   58,   58,   58,   58,  210,   67,   58,
       58,   58,   58,  207,   68,   58,   58,   58,   58,   58,
       58,   58,   58,   40,  140,  140,   69,   58,   58,   58,
       58,  146,  146,  206,   70,  149,  149,   42,   71,  150,
      150,   72,   58,   58,   58,   58,   73,  170,  170,   75,
       80,  200,   81,   74,   58,   58,   58,   58,   38,   86,

      199,   87,   91,   91,   91,   91,  142,   82,  110,  111,
      111,  111,   83,   76,  141,   84,   88,  139,   77,  173,
      173,   89,  174,  174,   90,   92,   93,   94,   94,   94,
       47,   47,   47,   47,  190,   95,   96,  189,  188,   97,
      101,   98,  187,   99,  109,  108,   95,  102,   96,  152,
      152,  152,  101,  106,  138,   97,  176,  176,  176,  103,
      103,  103,  103,   98,   92,   94,   94,   94,   94,  104,
      112,  112,  112,  112,   42,   96,   58,   58,   58,   58,
      169,  104,  100,   58,   58,   58,   58,   96,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   42,  113,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
      168,   38,  165,  114,   38,  164,  115,  116,   58,   58,
       58,   58,  105,  142,  141,  117,   58,   58,   58,   58,
      139,   58,   58,   58,   58,  118,   58,   58,   58,   58,
       58,   58,   58,   58,   91,   91,   91,   91,  138,  133,
      132,  119,  120,  131,  134,  130,  128,  136,  136,  136,
      136,  135,  127,  126,  121,  123,  134,  137,  125,   62,
      122,  143,  144,  144,  144,  145,  145,  145,  145,  137,

      147,  147,  147,  147,  103,  103,  103,  103,  111,  111,
      111,  111,   41,  109,  104,  151,  151,  151,  151,  108,
      106,  148,  153,  153,  153,  153,  104,  111,  111,  111,
      111,  112,  112,  112,  112,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,  105,   85,  155,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   62,  156,
       58,   58,   58,   58,  171,  171,  171,  171,  136,  136,
      136,  136,  157,   41,   41,  158,  160,   37,  137,  144,

      144,  144,  144,  214,  159,  172,  214,  161,   38,   38,
      137,   38,   39,   38,   38,  214,   38,   38,   38,  162,
      162,  162,  162,   38,   38,   38,   38,  163,  163,  163,
      163,  163,  163,  163,  163,   40,  163,   38,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,   38,   38,   42,
       42,  214,   42,  214,   42,   42,   39,   42,   42,   42,
      166,  166,  166,  166,   42,   42,   42,   42,  167,  167,
      167,  167,  167,  167,  167,  167,   43,  167,   42,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,

      167,  167,  167,  167,  167,  167,  167,  167,   42,   42,
      175,  175,  175,  175,  177,  177,  177,  177,  144,  144,
      144,  144,  145,  145,  145,  145,  179,  179,  179,  179,
      147,  147,  147,  147,  180,  180,  180,  180,  214,  214,
      101,  181,  181,  181,  181,  214,  214,  102,  151,  151,
      151,  151,  101,  153,  153,  153,  153,   58,   58,   58,
       58,   58,   58,   58,   58,  182,   58,   58,   58,   58,
      109,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,  183,  191,  191,  191,  191,  184,   58,
       58,   58,   58,  192,  192,  192,  192,  171,  171,  171,

      171,  193,  193,  193,  193,  214,  185,  134,  214,  214,
      214,  186,   38,   38,  135,   38,   39,   38,   38,  134,
       38,   38,   38,  175,  175,  175,  175,   38,   38,   38,
       38,  177,  177,  177,  177,  179,  179,  179,  179,   40,
      194,   38,  214,  180,  180,  180,  180,  214,  142,  214,
      214,  214,  195,  104,  197,  197,  197,  197,  214,  214,
      148,   38,   38,   42,   42,  104,   42,  214,   42,   42,
       39,   42,   42,   42,  181,  181,  181,  181,   42,   42,
       42,   42,   58,   58,   58,   58,   58,   58,   58,   58,
       43,  196,   42,   58,   58,   58,   58,   58,   58,   58,

       58,  191,  191,  191,  191,  192,  192,  192,  192,  214,
      214,  214,   42,   42,  214,  137,  214,  214,  201,  214,
      214,  198,  172,  193,  193,  193,  193,  137,  203,  203,
      203,  203,  204,  204,  204,  204,  205,  205,  205,  205,
      202,  197,  197,  197,  197,   58,   58,   58,   58,  208,
      208,  208,  208,  209,  209,  209,  209,  214,  182,  203,
      203,  203,  203,  204,  204,  204,  204,  205,  205,  205,
      205,  208,  208,  208,  208,  214,  194,  214,  214,  214,
      195,  214,  214,  214,  196,  214,  214,  214,  201,  209,
      209,  209,  209,  214,  214,  214,  214,  214,  214,  214,

      214,  214,  214,  214,  214,  214,  202,   38,  214,   38,
      214,   38,   38,   38,   38,   38,   38,   42,  214,  214,
       42,   42,   42,   42,   42,   42,   42,   59,   59,   59,
       59,  214,   59,   60,  214,   60,   60,   60,   60,   60,
       60,   60,   60,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   38,   38,  214,  214,  214,   38,   38,
       38,   42,   42,  214,  214,  214,   42,   42,   42,  124,
      124,  124,  214,  124,  129,  129,  129,  214,  129,  154,
      154,  214,  214,  214,  154,  178,  178,  214,  214,  214,
      178,  162,  214,  162,  214,  162,  162,  162,  162,  162,

      162,  166,  214,  214,  166,  166,  166,  166,  166,  166,
      166,    3,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214
    } ;

static yyconst short int yy_chk[1064] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    8,   11,   16,   12,   12,   12,   12,   12,
       13,   13,   13,   13,    6,   17,   17,   16,   19,   19,
       42,   34,   79,   11,   38,    8,   12,   14,   14,   14,
       14,   14,   20,   20,   20,   20,   36,   14,   14,   34,
       42,   14,   79,   14,  213,   14,   49,   38,   14,   36,

       14,   23,   23,   23,   23,   52,   52,   14,   24,   24,
       24,   24,  212,   49,   93,   14,   15,   15,   15,   15,
       15,   25,   25,   25,   25,   39,  211,   15,   39,   23,
       24,   93,  210,   23,   15,   26,   26,   26,   26,   15,
       78,  207,   24,   27,   27,   27,   27,  206,   25,   28,
       28,   28,   28,  200,   26,   29,   29,   29,   29,   30,
       30,   30,   30,   78,   96,   96,   27,   31,   31,   31,
       31,  101,  101,  199,   28,  104,  104,  190,   28,  106,
      106,   29,   32,   32,   32,   32,   29,  134,  134,   31,
       40,  189,   40,   30,   33,   33,   33,   33,  188,   43,

      187,   43,   44,   44,   44,   44,  178,   40,   55,   55,
       55,   55,   40,   32,  176,   40,   43,  174,   33,  137,
      137,   43,  139,  139,   43,   45,   45,   45,   45,   45,
       47,   47,   47,   47,  169,   45,   45,  168,  165,   45,
       47,   45,  164,   45,  154,  152,   45,   47,   45,  108,
      108,  108,   47,  150,  144,   45,  141,  141,  141,   48,
       48,   48,   48,   45,   46,   46,   46,   46,   46,   48,
       56,   56,   56,   56,  133,   46,   58,   58,   58,   58,
      132,   48,   46,   59,   59,   59,   59,   46,   63,   63,
       63,   63,   64,   64,   64,   64,   65,   65,   65,   65,

       66,   66,   66,   66,   67,   67,   67,   67,  131,   63,
       68,   68,   68,   68,   69,   69,   69,   69,   70,   70,
       70,   70,   71,   71,   71,   71,   72,   72,   72,   72,
      130,  128,  127,   66,  126,  125,   67,   68,   73,   73,
       73,   73,  111,   98,   97,   70,   74,   74,   74,   74,
       95,   75,   75,   75,   75,   71,   76,   76,   76,   76,
       77,   77,   77,   77,   91,   91,   91,   91,   94,   90,
       89,   74,   75,   88,   91,   87,   84,   92,   92,   92,
       92,   91,   83,   82,   75,   77,   91,   92,   81,   61,
       76,   99,   99,   99,   99,  100,  100,  100,  100,   92,

      102,  102,  102,  102,  103,  103,  103,  103,  105,  105,
      105,  105,   57,   54,  103,  107,  107,  107,  107,   53,
       51,  103,  109,  109,  109,  109,  103,  110,  110,  110,
      110,  112,  112,  112,  112,  113,  113,  113,  113,  114,
      114,  114,  114,  115,  115,  115,  115,  116,  116,  116,
      116,  117,  117,  117,  117,  118,  118,  118,  118,  119,
      119,  119,  119,   50,   41,  115,  120,  120,  120,  120,
      121,  121,  121,  121,  122,  122,  122,  122,   22,  116,
      123,  123,  123,  123,  135,  135,  135,  135,  136,  136,
      136,  136,  119,   10,    9,  120,  122,    7,  136,  138,

      138,  138,  138,    3,  121,  136,    0,  123,  124,  124,
      136,  124,  124,  124,  124,    0,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  129,
      129,    0,  129,    0,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,

      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      140,  140,  140,  140,  142,  142,  142,  142,  143,  143,
      143,  143,  145,  145,  145,  145,  146,  146,  146,  146,
      147,  147,  147,  147,  148,  148,  148,  148,    0,    0,
      147,  149,  149,  149,  149,    0,    0,  147,  151,  151,
      151,  151,  147,  153,  153,  153,  153,  155,  155,  155,
      155,  156,  156,  156,  156,  151,  157,  157,  157,  157,
      153,  158,  158,  158,  158,  159,  159,  159,  159,  160,
      160,  160,  160,  156,  170,  170,  170,  170,  157,  161,
      161,  161,  161,  172,  172,  172,  172,  171,  171,  171,

      171,  173,  173,  173,  173,    0,  159,  171,    0,    0,
        0,  161,  162,  162,  171,  162,  162,  162,  162,  171,
      162,  162,  162,  175,  175,  175,  175,  162,  162,  162,
      162,  177,  177,  177,  177,  179,  179,  179,  179,  162,
      175,  162,    0,  180,  180,  180,  180,    0,  177,    0,
        0,    0,  179,  180,  182,  182,  182,  182,    0,    0,
      180,  162,  162,  166,  166,  180,  166,    0,  166,  166,
      166,  166,  166,  166,  181,  181,  181,  181,  166,  166,
      166,  166,  183,  183,  183,  183,  184,  184,  184,  184,
      166,  181,  166,  185,  185,  185,  185,  186,  186,  186,

      186,  191,  191,  191,  191,  192,  192,  192,  192,    0,
        0,    0,  166,  166,    0,  192,    0,    0,  191,    0,
        0,  185,  192,  193,  193,  193,  193,  192,  194,  194,
      194,  194,  195,  195,  195,  195,  196,  196,  196,  196,
      193,  197,  197,  197,  197,  198,  198,  198,  198,  201,
      201,  201,  201,  202,  202,  202,  202,    0,  197,  203,
      203,  203,  203,  204,  204,  204,  204,  205,  205,  205,
      205,  208,  208,  208,  208,    0,  203,    0,    0,    0,
      204,    0,    0,    0,  205,    0,    0,    0,  208,  209,
      209,  209,  209,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,  209,  215,    0,  215,
        0,  215,  215,  215,  215,  215,  215,  216,    0,    0,
      216,  216,  216,  216,  216,  216,  216,  217,  217,  217,
      217,    0,  217,  218,    0,  218,  218,  218,  218,  218,
      218,  218,  218,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  220,  220,    0,    0,    0,  220,  220,
      220,  221,  221,    0,    0,    0,  221,  221,  221,  222,
      222,  222,    0,  222,  223,  223,  223,    0,  223,  224,
      224,    0,    0,    0,  224,  225,  225,    0,    0,    0,
      225,  226,    0,  226,    0,  226,  226,  226,  226,  226,

      226,  227,    0,    0,  227,  227,  227,  227,  227,  227,
      227,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gampil.l"
#define INITIAL 0
#line 2 "gampil.l"
#include <stdio.h>
#include "../parser/y.tab.h"

/*
Source : https://stackoverflow.com/questions/25395251/detecting-and-skipping-line-comments-with-flex
*/
#line 678 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 44 "gampil.l"

#line 831 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 215 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1012 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 45 "gampil.l"
{ return StringItem; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "gampil.l"
{return SingleComment; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "gampil.l"
{return MultiComment; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "gampil.l"
{return Assignment; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "gampil.l"
{return Be; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 50 "gampil.l"
{return If; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 51 "gampil.l"
{return But; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 52 "gampil.l"
{return Else; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 53 "gampil.l"
{return Ok; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 54 "gampil.l"
{return And; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 55 "gampil.l"
{return Or; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 56 "gampil.l"
{return Not; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 57 "gampil.l"
{return Redo; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 58 "gampil.l"
{return Quite; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 59 "gampil.l"
{return As; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 60 "gampil.l"
{return While; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 61 "gampil.l"
{return Return; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 62 "gampil.l"
{return Nil; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 63 "gampil.l"
{return True; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 64 "gampil.l"
{return False; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 65 "gampil.l"
{return IntegerItem; } 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 66 "gampil.l"
{return FloatItem; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 67 "gampil.l"
{return ArithmeticOperator; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 68 "gampil.l"
{return RelationalOperator; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 69 "gampil.l"
{return BitwiseOperator; } 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 70 "gampil.l"
{ return Iden; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 71 "gampil.l"
{return Other;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 72 "gampil.l"
{;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 73 "gampil.l"
{return *yytext; };
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 74 "gampil.l"
ECHO;
	YY_BREAK
#line 1064 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 215 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 215 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 214);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 74 "gampil.l"


int yywrap() {
    return 1;
}
