/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_main(unsigned char** args);
short add(short a, short b);
void greet();


short add(short a, short b) {
(void)a;
(void)b;
    return (a + b);
}

void greet() {
    printf("Greetings!");
}

void _gampil_main(unsigned char** args) {
    (void)args;
    printf("Hello World!");
    float y = 0.5;
    short x;
    x = 3LL;
    short z = 4LL;
    printf("added: %d\\n", add(z, x));
    printf("added: %d\\n", add(z, 0LL));
    short num[3] = {1LL, 3LL, 5LL};
    long* num2 = 0 /*unsupported expr 29*/;
    short* num3 = &x;
    struct { long long _0; unsigned char* _1; } user = {1LL, "John Doe"};
    struct { short id; unsigned char* name; long long _2; long long _3; unsigned char* _4; } hash = {2LL, "John Doe", 6LL, 7LL, "hello"};
    printf("%d\\n", num[0LL]);
    printf("%d\\n", user._0);
    printf("%d\\n", hash.id);
    printf("%d\\n", num3[0LL]);
    /* --- Parallel Guard Block --- */
    {
        int _guard0 = (
(x > 5LL));
        int _guard1 = (
(x == 5LL));
        int _guard2 = (
(x <= 5LL));
        int _guard3 = (
(x >= 5LL));
        if (_guard3) { _guard0 = 0; _guard1 = 0; _guard2 = 0; }
        if (_guard0) {
            printf("Higher than 5\\n", "\n");
        }
        if (_guard1) {
            printf("Equal to 5\\n", "\n");
        }
        if (_guard2) {
            printf("Less than 5\\n", "\n");
        }
        if (_guard3) {
            printf("Exclusion found!", "\n");
        }
    } /* --- end Guard Block --- */
    for (int _idx_i = 0; _idx_i < 3; _idx_i++) {
        short i = num[_idx_i];
        printf("Looping1\\n", "\n");
    }
    for (int _idx_j = 0; _idx_j < 3; _idx_j++) {
        short j = num[_idx_j];
        printf("Looping2", "\n");
        break;
    }
    while (1) {
        if ((!(x) >= 0LL)) {
            break;
        }
        x -= 1LL;
    }
    while ((x < 5LL)) {
        x = (x + 1LL);
    }
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_main((unsigned char**)argv);
    return 0;
}
