/* Auto-generated by Gampil Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>

/* --- Forward Declarations --- */
void _gampil_main(unsigned char** args);
short add(short a, short b);
void greet();


short add(short a, short b) {
(void)a;
(void)b;
    return (a + b);
}

void greet() {
    printf("Greetings!");
}

void _gampil_main(unsigned char** args) {
    (void)args;
    printf("Hello World!");
    float y = 0.5;
    short x;
    x = 3;
    short z = 4;
    printf("added: %d\\n", add(z, x));
    printf("added: %d\\n", add(z, 0));
    short num[3] = {1, 3, 5};
    long* num2 = 0 /*unsupported expr 29*/;
    short* num3 = &x;
    struct { long _0; unsigned char* _1; } user = {1, "John Doe"};
    struct { short id; unsigned char* name; long _2; long _3; unsigned char* _4; } hash = {2, "John Doe", 6, 7, "hello"};
    printf("%d\\n", num[0]);
    printf("%d\\n", user._0);
    printf("%d\\n", hash.id);
    printf("%d\\n", num3[0]);
    /* --- Parallel Guard Block --- */
    {
        int _else_flag = 1;
        int _guard0 = ((x > 5));
        if (_guard0) _else_flag = 0;
        int _guard1 = ((x == 5));
        if (_guard1) _else_flag = 0;
        int _guard2 = ((x <= 5));
        if (_guard2) _else_flag = 0;
        int _guard3 = ((_else_flag && (x >= 5)));
        if (_guard3) _else_flag = 0;
        if (_guard0) {
            printf("Higher than 5\\n", "\n");
        }
        if (_guard1) {
            printf("Equal to 5\\n", "\n");
        }
        if (_guard2) {
            printf("Less than 5\\n", "\n");
        }
        if (_guard3) {
            printf("Exclusion found!", "\n");
        }
    } /* --- end Guard Block --- */
    {
        for (int _idx_52 = 0; _idx_52 < 3; _idx_52++) {
            short i = num[_idx_52];
            printf("Looping1\\n", "\n");
        }
    }
    {
        for (int _idx_56 = 0; _idx_56 < 3; _idx_56++) {
            short j = num[_idx_56];
            printf("Looping2", "\n");
            break;
        }
    }
    while (1) {
        /* --- Parallel Guard Block --- */
        {
            int _else_flag = 1;
            int _guard0 = ((!(x) >= 0));
            if (_guard0) _else_flag = 0;
            if (_guard0) {
                break;
            }
        } /* --- end Guard Block --- */
        x -= 1;
    }
    while ((x < 5)) {
        x = (x + 1);
    }
}

int main(int argc, char** argv) {
    (void)argc;
    _gampil_main((unsigned char**)argv);
    return 0;
}
